const std = @import("std");
const mlir = @import("wrapper.zig");
const c = @import("c.zig").c;

const Allocator = std.mem.Allocator;

const TILING_TRANSFORM_SCRIPT =
    \\module attributes { transform.with_named_sequence } {
    \\  transform.named_sequence @__transform_main(%arg0: !transform.any_op) {
    \\    transform.sequence %arg0 : !transform.any_op failures(propagate) {
    \\      ^bb1(%arg1: !transform.any_op):
    \\        %matmul = transform.structured.match ops{["linalg.generic"]} attributes {iterator_types = ["parallel", "parallel", "parallel", "reduction"]} in %arg1 : (!transform.any_op) -> !transform.any_op
    \\        %init_or_alloc_op, %more_parallel_fill_op, %split_matmul, %combining_linalg_op = transform.structured.split_reduction %matmul {split_factor = 8, insert_split_dimension = 3} : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.any_op, !transform.any_op)
    \\        %tiled_split, %forall_split = transform.structured.tile_using_forall %split_matmul tile_sizes [8, 64, 64, 16, 0]
    \\          (mapping = [#gpu.block<x>, #gpu.block<y>, #gpu.thread<x>, #gpu.thread<y>]) : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
    \\        %tiled_fill, %forall_fill = transform.structured.tile_using_forall %more_parallel_fill_op tile_sizes [8, 64, 64, 16]
    \\          (mapping = [#gpu.block<x>, #gpu.block<y>, #gpu.thread<x>, #gpu.thread<y>]) : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
    \\        %tiled_combine, %forall_combine = transform.structured.tile_using_forall %combining_linalg_op tile_sizes [8, 64, 64]
    \\          (mapping = [#gpu.block<x>, #gpu.block<y>, #gpu.thread<x>]) : (!transform.any_op) -> (!transform.any_op, !transform.any_op)
    \\    }
    \\    transform.yield
    \\  }
    \\}
;

const GPU_MAPPING_SCRIPT =
    \\module attributes { transform.with_named_sequence } {
    \\  transform.named_sequence @__transform_main(%arg0: !transform.any_op) {
    \\    %func = transform.structured.match ops{["func.func"]} in %arg0 : (!transform.any_op) -> !transform.any_op
    \\    transform.gpu.map_forall_to_blocks %func { generate_gpu_launch } : (!transform.any_op) -> !transform.any_op
    \\    transform.gpu.map_nested_forall_to_threads %func block_dims = [64, 4, 1] sync_after_distribute = false warp_size = 1 : (!transform.any_op) -> !transform.any_op
    \\    transform.yield
    \\  }
    \\}
;

/// MLIR Context wrapper for StableHLO → GPU → SPIR-V pipeline
pub const MLIRContext = struct {
    allocator: Allocator,
    context: c.MlirContext,
    registry: ?c.MlirDialectRegistry,

    // --- REMOVED ---
    // pass_manager: mlir.PassManager, // <-- This field is the source of the state bug. Remove it.

    const Self = @This();

    pub fn init(allocator: Allocator) !Self {
        std.debug.print("MLIRContext.init: Creating IREE-backed MLIR context...\n", .{});
        const context = c.contextCreate();
        c.contextSetAllowUnregisteredDialects(context, true);

        // --- START OF THE FIX ---
        // Instead of relying on automatic discovery, we will now explicitly
        // register and load the dialects we need.

        // 1. Create a dialect registry.
        const registry = c.dialectRegistryCreate();
        defer c.dialectRegistryDestroy(registry);

        // 2. Insert the dialects we need into the registry.
        //    This calls the C functions generated by our new pass_anchors.cpp
        std.debug.print("Inserting dialects into registry...\n", .{});
        c.mlirDialectHandleInsertDialect(c.mlirGetDialectHandle__func__(), registry);
        c.mlirDialectHandleInsertDialect(c.mlirGetDialectHandle__stablehlo__(), registry);
        c.mlirDialectHandleInsertDialect(c.mlirGetDialectHandle__arith__(), registry);

        // 3. Append the configured registry to the context.
        std.debug.print("Appending registry to context...\n", .{});
        c.contextAppendDialectRegistry(context, registry);

        // 4. Also try loading all available dialects as fallback
        std.debug.print("Loading all available dialects...\n", .{});
        c.contextLoadAllAvailableDialects(context);
        // --- END OF THE FIX ---

        // Now, our check will succeed because we have explicitly loaded the dialect.
        std.debug.print("Checking if stablehlo.constant operation is registered...\n", .{});
        const constant_name = c.stringRefFromString("stablehlo.constant");
        if (!c.contextIsRegisteredOperation(context, constant_name)) {
            // Try alternative operation names
            std.debug.print("stablehlo.constant not found, trying stablehlo.add...\n", .{});
            const add_name = c.stringRefFromString("stablehlo.add");
            if (!c.contextIsRegisteredOperation(context, add_name)) {
                std.log.err("FATAL: Stablehlo dialect not registered. Check IREE build and linking.", .{});
                return error.DialectRegistrationFailed;
            }
        }
        std.debug.print("StableHLO dialect successfully registered!\n", .{});

        return Self{
            .allocator = allocator,
            .context = context,
            .registry = null, // We are not managing the registry after appending it.
        };
    }

    /// Create an MLIRContext wrapper from an existing MLIR context
    /// This avoids double initialization when sharing contexts between components
    pub fn fromContext(context: mlir.Context) Self {
        // Create a minimal wrapper that doesn't own the context
        // The registry is set to null since we're not managing it
        return Self{
            .allocator = std.heap.page_allocator, // Dummy allocator since we're not managing resources
            .context = context.handle,
            .registry = null, // Not managing the registry
        };
    }

    pub fn deinit(self: *Self) void {
        // self.pass_manager.deinit(); // <-- Remove this.
        if (self.registry) |registry| {
            c.dialectRegistryDestroy(registry);
        }
        // Only destroy context if we own it (registry is not null)
        if (self.registry != null) {
            c.contextDestroy(self.context);
        }
    }

    /// Compiles an MLIR module to a VMFB artifact using the IREE compiler.
    /// amd_target: Optional AMD GPU target architecture (e.g., "gfx942" for MI300X)
    pub fn compileToVMFB(self: *Self, allocator: Allocator, mlir_source: []const u8, iree_target: []const u8, amd_target: ?[]const u8) ![]u8 {
        _ = self;

        // 2. Create unique temporary file paths
        const timestamp = std.time.timestamp();
        const temp_mlir_path = try std.fmt.allocPrint(allocator, "/tmp/pcp_module_{d}.mlir", .{timestamp});
        defer allocator.free(temp_mlir_path);
        const temp_vmfb_path = try std.fmt.allocPrint(allocator, "/tmp/pcp_module_{d}.vmfb", .{timestamp});
        defer allocator.free(temp_vmfb_path);

        // Write transform dialect scripts to temp files
        const temp_tiling_path = try std.fmt.allocPrint(allocator, "/tmp/pcp_tiling_{d}.mlir", .{timestamp});
        defer allocator.free(temp_tiling_path);
        const temp_mapping_path = try std.fmt.allocPrint(allocator, "/tmp/pcp_mapping_{d}.mlir", .{timestamp});
        defer allocator.free(temp_mapping_path);

        try std.fs.cwd().writeFile(.{ .sub_path = temp_tiling_path, .data = TILING_TRANSFORM_SCRIPT });
        try std.fs.cwd().writeFile(.{ .sub_path = temp_mapping_path, .data = GPU_MAPPING_SCRIPT });

        // 3. Write MLIR to temporary file
        try std.fs.cwd().writeFile(.{ .sub_path = temp_mlir_path, .data = mlir_source });

        // 4. Call the IREE compiler as a subprocess
        const iree_compile_path = "iree-compile";

        const target_arg = try std.fmt.allocPrint(allocator, "--iree-hal-target-backends={s}", .{iree_target});
        defer allocator.free(target_arg);

        const is_rocm = std.mem.eql(u8, iree_target, "rocm") or std.mem.eql(u8, iree_target, "hip");
        const is_cuda = std.mem.eql(u8, iree_target, "cuda");

        var argv = std.ArrayList([]const u8).init(allocator);
        defer argv.deinit();

        var hip_target_arg: ?[]u8 = null;
        var cuda_arch_arg: ?[]u8 = null;
        // var tiling_flag: ?[]u8 = null;
        // var dump_dir: ?[]u8 = null;
        defer if (hip_target_arg) |arg| allocator.free(arg);
        defer if (cuda_arch_arg) |arg| allocator.free(arg);
        // defer if (tiling_flag) |arg| allocator.free(arg);
        // defer if (dump_dir) |arg| allocator.free(arg);

        try argv.append(iree_compile_path);
        try argv.append(temp_mlir_path);
        try argv.append(target_arg);

        // Handle architecture targets
        if (is_rocm and amd_target != null) {
            hip_target_arg = try std.fmt.allocPrint(allocator, "--iree-hip-target={s}", .{amd_target.?});
            try argv.append(hip_target_arg.?);
            std.log.info("Compiling for AMD target: {s}", .{amd_target.?});
        } else if (is_cuda) {
            cuda_arch_arg = try std.fmt.allocPrint(allocator, "--iree-cuda-target=sm_80", .{});
            try argv.append(cuda_arch_arg.?);

            // Disable all advanced CUDA codegen features to avoid LLVM lowering issues
            try argv.append("--iree-codegen-llvmgpu-use-vector-distribution=false");
            try argv.append("--iree-codegen-llvmgpu-use-reduction-vector-distribution=false");
        }

        // Apply transform dialect scripts for GPU targets
        // COMMENTED OUT: Transform scripts causing CUDA compilation to hang
        // if (is_cuda or is_rocm) {
        //     tiling_flag = try std.fmt.allocPrint(allocator, "--iree-codegen-transform-dialect-library={s}", .{temp_tiling_path});
        //     try argv.append(tiling_flag.?);

        //     // Enable debugging: dump intermediates to /tmp/dumps
        //     dump_dir = try std.fmt.allocPrint(allocator, "--iree-hal-dump-executable-intermediates-to=/tmp/dumps_{d}", .{timestamp});
        //     try argv.append(dump_dir.?);

        //     std.log.info("Using transform scripts: tiling={s}", .{temp_tiling_path});
        // }

        // --- FIXES FOR NanoGPT COMPILATION ---

        // 1. Enable 64-bit indexing (Required for large models)
        try argv.append("--iree-vm-target-index-bits=64");
        try argv.append("--iree-stream-resource-index-bits=64");
        try argv.append("--iree-input-demote-i64-to-i32=false");

        // 2. Disable prefetching
        try argv.append("--iree-llvmgpu-enable-prefetch=false");

        try argv.append("-o");
        try argv.append(temp_vmfb_path);

        std.log.info("Compiling with flags: {s}", .{argv.items});

        const result = std.process.Child.run(.{
            .allocator = allocator,
            .argv = argv.items,
            .max_output_bytes = 100 * 1024 * 1024, // 100MB limit for stderr/stdout
        }) catch |err| {
            std.log.err("Failed to execute `iree-compile`: {s}", .{@errorName(err)});
            return err;
        };
        defer allocator.free(result.stdout);
        defer allocator.free(result.stderr);

        if (result.term != .Exited or result.term.Exited != 0) {
            std.log.err("IREE compilation failed with stdout:\n{s}", .{result.stdout});
            std.log.err("IREE compilation failed with stderr:\n{s}", .{result.stderr});
            std.log.err("MLIR Source saved to: {s}", .{temp_mlir_path});
            return error.IREECompilationFailed;
        }

        const vmfb_binary = try std.fs.cwd().readFileAlloc(allocator, temp_vmfb_path, 50 * 1024 * 1024); // 50MB limit

        // Cleanup temp files
        std.fs.deleteFileAbsolute(temp_mlir_path) catch {};
        std.fs.deleteFileAbsolute(temp_vmfb_path) catch {};
        std.fs.deleteFileAbsolute(temp_tiling_path) catch {};
        std.fs.deleteFileAbsolute(temp_mapping_path) catch {};

        return vmfb_binary;
    }

    /// Get the MLIR context handle for creating modules
    pub fn getContext(self: *Self) mlir.Context {
        return mlir.Context{ .handle = self.context };
    }
};

/// Serialize an MLIR module to a string representation for network transfer.
pub fn serializeMLIRModule(allocator: Allocator, module: mlir.Module) ![]u8 {
    // Debug: std.debug.print("serializeMLIRModule: Creating buffer...\n", .{});
    var buffer = std.ArrayList(u8).init(allocator);
    var serialization_error = false;

    const SerializationContext = struct {
        buffer: *std.ArrayList(u8),
        error_flag: *bool,
    };

    var ctx = SerializationContext{
        .buffer = &buffer,
        .error_flag = &serialization_error,
    };

    const writeToArrayList = struct {
        fn callback(string_ref: c.MlirStringRef, userData: ?*anyopaque) callconv(.C) void {
            const context = @as(*SerializationContext, @ptrCast(@alignCast(userData.?)));
            const data = c.fromStringRef(string_ref);

            // Debug: std.debug.print("MLIR serialization callback: appending {} bytes (total so far: {})\n", .{ data.len, context.buffer.items.len });

            // Add bounds checking to prevent buffer overflow
            if (data.len > 100 * 1024 * 1024) { // 100MB sanity check
                std.debug.print("ERROR: MLIR serialization data chunk too large: {} bytes\n", .{data.len});
                context.error_flag.* = true;
                return;
            }
            context.buffer.appendSlice(data) catch |err| {
                std.debug.print("ERROR: Failed to append MLIR data chunk of {} bytes: {}\n", .{ data.len, err });
                context.error_flag.* = true;
                return;
            };
        }
    }.callback;

    // Debug: std.debug.print("serializeMLIRModule: About to call mlirOperationPrint...\n", .{});
    // Add null checks
    const module_op = module.op();
    if (@intFromPtr(module_op.handle.ptr) == 0) {
        std.debug.print("ERROR: Module operation handle is null\n", .{});
        return error.NullModuleHandle;
    }

    c.mlirOperationPrint(module_op.handle, writeToArrayList, &ctx);
    // Debug: std.debug.print("serializeMLIRModule: mlirOperationPrint completed, buffer size: {}\n", .{buffer.items.len});

    // Check if any errors occurred during serialization
    if (serialization_error) {
        std.debug.print("ERROR: MLIR serialization failed due to callback errors\n", .{});
        buffer.deinit();
        return error.MLIRSerializationFailed;
    }

    const serialized = buffer.toOwnedSlice() catch |err| {
        std.debug.print("ERROR: Failed to convert buffer to owned slice: {}\n", .{err});
        return err;
    };
    std.debug.print("✓ Serialized MLIR module to {} bytes\n", .{serialized.len});
    return serialized;
}
